# Generated by Django 4.0.3 on 2022-03-16 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mechanics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PublishingHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('minimum_players', models.SmallIntegerField()),
                ('maximum_players', models.SmallIntegerField()),
                ('age', models.SmallIntegerField()),
                ('categories', models.ManyToManyField(to='BoardGameSiteApp.category')),
                ('mechanics', models.ManyToManyField(to='BoardGameSiteApp.mechanics')),
                ('publishing_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BoardGameSiteApp.publishinghouse')),
            ],
        ),
    ]
