# Generated by Django 4.0.3 on 2022-03-16 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BoardGameSiteApp', '0002_alter_category_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='age',
            new_name='minimum_age',
        ),
    ]
