# Generated by Django 4.0.3 on 2022-03-18 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoardGameSiteApp', '0004_rename_mechanics_mechanic'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='name_pl',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
    ]
