# Generated by Django 4.0.3 on 2022-03-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoardGameSiteApp', '0005_mechanic_name_pl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
