# Generated by Django 4.0.3 on 2022-03-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoardGameSiteApp', '0006_alter_game_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
