# Generated by Django 4.0.3 on 2022-04-02 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BoardGameSiteApp', '0014_alter_game_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelfgame',
            name='comment',
        ),
    ]
