# Generated by Django 4.0.3 on 2022-04-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoardGameSiteApp', '0016_gamecategory_gamemechanic_alter_game_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='games',
            field=models.ManyToManyField(null=True, through='BoardGameSiteApp.ShelfGame', to='BoardGameSiteApp.game'),
        ),
    ]
