# Generated by Django 4.0.3 on 2022-04-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoardGameSiteApp', '0017_alter_shelf_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelf',
            name='games',
            field=models.ManyToManyField(through='BoardGameSiteApp.ShelfGame', to='BoardGameSiteApp.game'),
        ),
    ]
