# Generated by Django 4.0.3 on 2022-04-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoardGameSiteApp', '0019_alter_shelf_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='APGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124)),
                ('price', models.FloatField()),
                ('link', models.TextField()),
                ('availability', models.BooleanField()),
                ('scarp_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
